board_size: 9
walls_per_player: 10

model:
  hidden_dim: 256
  num_blocks: 6
  use_compile: true

training:
  num_self_play_games: 400
  batch_size: 256
  lr: 0.001
  num_iterations: 100
  buffer_size: 50000
  num_workers: 12

mcts:
  num_simulations: 400
  c_puct: 1.5
  temperature: 1.0
  dirichlet_noise_alpha: 0.3
  dirichlet_noise_epsilon: 0.25
